import random
import json
import os

def clear():
    os.system('cls' if os.name == 'nt' else 'clear')

# rarity:weight
with open("rarities.json") as file:
    possible = json.load(file)

def roll():
    simulation = int(input("how many rolls? "))
    returns = []
    for i in range(simulation):
        rarity = random.choices(list(possible.keys()), weights=possible.values())[0]
        returns.append(rarity)
    print("rolled, counting...")
        
    for x in returns:
        commons = returns.count("common")
        print("counted common")
        clear()
        uncommons = returns.count("uncommon")
        print("counted uncommon")
        clear()
        rares = returns.count("rare")
        print("counted rare")
        clear()
        epic = returns.count("very rare")
        print("counted very rare")
        clear()
        legendaries = returns.count("legendary")
        print("counted legendary")
        clear()
        mythical = returns.count("mythical")
        print("counted mythical")
        clear()
        perfect = returns.count("perfect")
        print("counted perfect")
        clear()
        heavenly = returns.count("heavenly")
        print("counted heavenly")
        clear()
        godly = returns.count("godly")
        print("counted godly")
        clear()
        otherworldly = returns.count("otherworldly")
        print("counted otherworldly")
        clear()
        sunlight = returns.count("sunlight")
        print("counted sunlight")
        clear()
        moonlight = returns.count("moonlight")
        print("counted moonlight")
        clear()
        stellar = returns.count("stellar")
        print("counted stellar")
        clear()
        cosmic = returns.count("cosmic")
        print("counted cosmic")
        clear()
        galactic = returns.count("galactic")
        print("counted galactic")
        clear()
        universal = returns.count("universal")
        print("counted universal")
        clear()
        celestial = returns.count("celestial")
        print("counted celestial")
        clear()
        millenial = returns.count("millenial")
        print("counted millenial")
        clear()
        eternal = returns.count("eternal")
        print("counted eternal")
        clear()
        divine = returns.count("divine")
        print("counted divine")
        clear()
        sacred = returns.count("sacred")
        print("counted sacred")
        clear()
        prismatic = returns.count("prismatic")
        print("counted prismatic")
        clear()
        radiant = returns.count("radiant")
        print("counted radiant")
        clear()
        illustrious = returns.count("illustrious")
        print("counted illustrious")
        clear()
        magnificent = returns.count("magnificent")
        print("counted magnificent")
        clear()
        shining = returns.count("shining")
        print("counted shining")
        clear()
        amethyst = returns.count("amethyst")
        print("counted amethyst")
        clear()
        emerald = returns.count("emerald")
        print("counted emerald")
        clear()
        ruby = returns.count("ruby")
        print("counted ruby")
        clear()
        sapphire = returns.count("sapphire")
        print("counted sapphire")
        clear()
        diamond = returns.count("diamond")
        print("counted diamond")
        clear()
        topaz = returns.count("topaz")
        print("counted topaz")
        clear()
        opal = returns.count("opal")
        print("counted opal")
        clear()
        pearl = returns.count("pearl")
        print("counted pearl")
        clear()
        clean = returns.count("clean")
        print("counted clean")
        clear()
        pristine = returns.count("pristine")
        print("counted pristine")
        clear()
        pure = returns.count("pure")
        print("counted pure")
        clear()
        flawless = returns.count("flawless")
        print("counted flawless")
        clear()
        whole = returns.count("whole")
        print("counted whole")
        clear()
        hollow = returns.count("hollow")
        print("counted hollow")
        clear()
        empty = returns.count("empty")
        print("counted empty")
        clear()
        void = returns.count("void")
        print("counted void")
        clear()
        dark = returns.count("dark")
        print("counted dark")
        clear()
        shadow = returns.count("shadow")
        print("counted shadow")
        clear()
        dusk = returns.count("dusk")
        print("counted dusk")
        clear()
        cruel = returns.count("cruel")
        print("counted cruel")
        clear()
        evil = returns.count("evil")
        print("counted evil")
        clear()
        mystic = returns.count("mystic")
        print("counted mystic")
        clear()
        magic = returns.count("magic")
        print("counted magic")
        clear()
        enchanted = returns.count("enchanted")
        print("counted enchanted")
        clear()
        charmed = returns.count("charmed")
        print("counted charmed")
        clear()
        cursed = returns.count("cursed")
        print("counted cursed")
        clear()
        bound = returns.count("bound")
        print("counted bound")
        clear()
        leashed = returns.count("leashed")
        print("counted leashed")
        clear()
        acidic = returns.count("acidic")
        print("counted acidic")
        clear()
        treasured = returns.count("treasured")
        print("counted treasured")
        clear()
        ancient = returns.count("ancient")
        print("counted ancient")
        clear()
        fabled = returns.count("fabled")
        print("counted fabled")
        clear()
        holy = returns.count("holy")
        print("counted holy")
        clear()
        unholy = returns.count("unholy")
        print("counted unholy")
        clear()
        true = returns.count("true")
        print("counted true")
        clear()
        hidden = returns.count("hidden")
        print("counted hidden")
        clear()
        failed = returns.count("failed")
        print("counted failed")
        clear()
        complete = returns.count("complete")
        print("counted complete")
        clear()
        
    print(f"common x{commons}")
    print(f"uncommon x{uncommons}")
    print(f"rare x{rares}")
    print(f"very rare x{epic}")
    print(f"legendary x{legendaries}")
    print(f"mythical x{mythical}")
    print(f"perfect x{perfect}")
    print(f"heavenly x{heavenly}")
    print(f"godly x{godly}")
    print(f"otherworldly x{otherworldly}")
    print(f"sunlight x{sunlight}")
    print(f"moonlight x{moonlight}")
    print(f"stellar x{stellar}")
    print(f"cosmic x{cosmic}")
    print(f"galactic x{galactic}")
    print(f"universal x{universal}")
    print(f"celestial x{celestial}")
    print(f"millenial x{millenial}")
    print(f"eternal x{eternal}")
    print(f"divine x{divine}")
    print(f"sacred x{sacred}")
    print(f"prismatic x{prismatic}")
    print(f"radiant x{radiant}")
    print(f"illustrious x{illustrious}")
    print(f"magnificent x{magnificent}")
    print(f"shining x{shining}")
    print(f"amethyst x{amethyst}")
    print(f"emerald x{emerald}")
    print(f"ruby x{ruby}")
    print(f"sapphire x{sapphire}")
    print(f"diamond x{diamond}")
    print(f"topaz x{topaz}")
    print(f"opal x{opal}")
    print(f"pearl x{pearl}")
    print(f"clean x{clean}")
    print(f"pristine x{pristine}")
    print(f"pure x{pure}")
    print(f"flawless x{flawless}")
    print(f"whole x{whole}")
    print(f"hollow x{hollow}")
    print(f"empty x{empty}")
    print(f"void x{void}")
    print(f"dark x{dark}")
    print(f"shadow x{shadow}")
    print(f"dusk x{dusk}")
    print(f"cruel x{cruel}")
    print(f"evil x{evil}")
    print(f"mystic x{mystic}")
    print(f"magic x{magic}")
    print(f"enchanted x{enchanted}")
    print(f"charmed x{charmed}")
    print(f"cursed x{cursed}")
    print(f"bound x{bound}")
    print(f"leashed x{leashed}")
    print(f"acidic x{acidic}")
    print(f"treasured x{treasured}")
    print(f"ancient x{ancient}")
    print(f"fabled x{fabled}")
    print(f"holy x{holy}")
    print(f"unholy x{unholy}")
    print(f"true x{true}")
    print(f"hidden x{hidden}")
    print(f"failed x{failed}")
    print(f"complete x{complete}")
    input()
    print("Press enter to spin again, or type 'exit' to leave.")

clear()
print("welcome to gambling sim 2")
print("press enter to spin, type 'exit' to leave.")
choice = input()
while choice.lower() != "exit":
    clear()
    roll()
    choice = input()
    if choice.lower() == "exit":
        break